### ISSUE TITLE
Roadmap for persisting sdk v2 MessageBundles

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#70]
MESDK-109

Capturing here for wider readability.

This tasklist describes the steps toward full persistence and apis for [v2 MessgaeBundles](https://github.com/opral/monorepo/pull/2700). This is part of an ongoing effort to streamline the sdk architecture as described in [https://github.com/opral/inlang-message-sdk/issues/15](https://github.com/opral/inlang-message-sdk/issues/15).

- [X] 1\. load/store JSON v2 MessageBundles under experimental persistence feature flag [PR 2801](https://github.com/opral/monorepo/pull/2801)
- [X] 2\. New [CRUD api](https://linear.app/opral/issue/MESDK-89/v2-messagebundle-query-apis-crud) for MessageBundles. This api will be async and non-reactive.
- [ ] 3\. Project-level `subscribe` api which does not depend on solidjs. [PR 2913](https://github.com/opral/monorepo/pull/2913)
- [ ] 4\. createMessageBundle, createMessage, createVariant helpers with auto-generated unique id's
- [ ] 5\. UI framework adapter(s) built on top of the async crud + subscribe api
- [ ] 6\. *Maybe* shim the existing [MessageQueryApi](https://github.com/opral/monorepo/blob/main/inlang/source-code/sdk/src/api.ts#L92-L113) exposing partial v2 MessageBundles to existing inlang apps for backward compatiblity.

![SDK reactive API(3)](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/02078617-20c2-4249-a9f0-5e47d70caa4e/02a38dda-8a72-47d0-ad13-7b1548e2951c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wMjA3ODYxNy0yMGMyLTQyNDktYTlmMC01ZTQ3ZDcwY2FhNGUvMDJhMzhkZGEtOGE3Mi00N2QwLWFkMTMtN2IxNTQ4ZTI5NTFjIiwiaWF0IjoxNzE2NDg0MDI1LCJleHAiOjMzMjg3MDQ0MDI1fQ.OldlrQDLltIl889_QTQtAHnTvpAjFFXbZBREYYieLBg)

**Comment by samuelstroschein** [comment]
Regarding the framework adapter: <br><br>Exposing RxJS Observables has high interop. The only "adapter" (just a binding function) that UI frameworks would need is to `.subscribe`. 

In Solid land this is as simple as:

```
function Component(){
  const message = from(project.query.message.subscribe("blabla"))
  return <>{message()}</>
}
```

[https://docs.solidjs.com/reference/reactive-utilities/from](https://docs.solidjs.com/reference/reactive-utilities/from)

In React land

```typescript
function Component(){
  const message = useObservable(project.query.message.subscribe("blabla"))
  return <>{message}</>
}
```

[https://github.com/crimx/observable-hooks](https://github.com/crimx/observable-hooks)

Hence, I think going with RxJS for internal reactivity and exposing observables via .subscribe is our easiest path to put the reactivity discussions behind us. cc @martin.lysk1

**Comment by martin-lysk** [comment]
Agree - any thoughts on this one from you @jan.johannes

**Comment by jldec** [comment]
Thanks for the feedback 🙏 <br>Here's a quick TL;DR of how I'm thinking about the api layers for now.<br>Internal means below the `===` line.

```plaintext
UI code
- - - - - - - - - - - - - - - - - -
UI framework adapter
- - - - - - - - - - - - - - - - - -
generic reactive api: RxJS ?
===================================
js subscribe (e.g. to CRUD events)
- - - - - - - - - - - - - - - - - -
messages CRUD api (not reactive)
- - - - - - - - - - - - - - - - - -
store api (DB/files)
```

To be extra clear @martin.lysk1, I don't think we want reactivity in the bottom layers, even knowing that we want observable database queries in the future.

At the time when we have lix apis for change-tracking on a DB, we can look at DBs with watchable queries, but I did not interpret @samuel.stroschein's suggestion for RxJS to mean that we should implement this in our v2 store using RxJS internally.

The v2 store is a *very* bare-bones database designed to live in text files versioned by git while we continue working on lix.

**Comment by samuelstroschein** [comment]
What is the generic reactive api? JS subscribe can be applied to any api no? <br><br>for example:<br>`project.settings.subscribe()`

i would prob also change the api to project.settings.get|set|subscribe:

```
project.settings.get()
project.settings.set()
project.settings.subscribe()
```

* future proofs API by avoiding breaking changes [https://github.com/opral/monorepo/issues/1680](https://github.com/opral/monorepo/issues/1680) 
* exposing subscriptions for all props become possible if apps need it. else they just use `get()` 
* no special framework adapter needed that wraps the entire api. only a utility function that maps `.subscribe()` to a frameowkrs reactive system is needed 

> but I did not interpret @samuel.stroschein's suggestion for RxJS to mean that we should implement this in our v2 store using RxJS internally.

Yep. Doesn't have to use rxjs internally BUT Ui state always needs to be correct. wiring everything manyally will be hard ( i assume). you can try a non rxjs implementation. if bugs pop up, we will know why

**Comment by samuelstroschein** [comment]
> change the api to project.{api}.get|set|subscribe
>>  Do you have a sense of where query() might fit in this model?

No. Except that we can prob drop the `.query.*` namespace.

```
project.messages.get()
project.messages.subscribe()
project.lintReports.update()
project.lintReports.subscribe()
```

> I do wonder how we might incorporate @felixhaeberle 's request for projectList.subscribe in [MESDK-36](https://linear.app/opral/issue/MESDK-36/)

Yep. probably with the same pattern.

```
listProjects.get()
listProject.subscribe()
```
